// GROQ queries for vehicle data

// Query to get all vehicles with essential fields
export const ALL_VEHICLES_QUERY = `*[_type == "vehicle" && status == "available"] | order(_createdAt desc) {
  _id,
  _type,
  title,
  year,
  make,
  model,
  trim,
  vin,
  stockNum,
  odometer,
  bodyType,
  engineDesc,
  transmission,
  drivetrain,
  fuelType,
  exteriorColor,
  interiorColor,
  price,
  salePrice,
  description,
  highlights,
  features,
  images,
  mpgCity,
  mpgHighway,
  warranty,
  financing,
  status,
  featured,
  slug
}`

// Query to get featured vehicles only
export const FEATURED_VEHICLES_QUERY = `*[_type == "vehicle" && status == "available" && featured == true] | order(_createdAt desc) {
  _id,
  _type,
  title,
  year,
  make,
  model,
  trim,
  vin,
  stockNum,
  odometer,
  bodyType,
  engineDesc,
  transmission,
  drivetrain,
  fuelType,
  exteriorColor,
  interiorColor,
  price,
  salePrice,
  description,
  highlights,
  features,
  images,
  mpgCity,
  mpgHighway,
  warranty,
  financing,
  status,
  featured,
  slug
}`

// Query to get a single vehicle by ID
export const VEHICLE_BY_ID_QUERY = `*[_type == "vehicle" && _id == $id][0] {
  _id,
  _type,
  title,
  year,
  make,
  model,
  trim,
  vin,
  stockNum,
  odometer,
  bodyType,
  engineDesc,
  transmission,
  drivetrain,
  fuelType,
  exteriorColor,
  interiorColor,
  price,
  salePrice,
  description,
  highlights,
  features,
  images,
  mpgCity,
  mpgHighway,
  warranty,
  financing,
  status,
  featured,
  slug
}`

// Query to get a single vehicle by slug
export const VEHICLE_BY_SLUG_QUERY = `*[_type == "vehicle" && slug.current == $slug][0] {
  _id,
  _type,
  title,
  year,
  make,
  model,
  trim,
  vin,
  stockNum,
  odometer,
  bodyType,
  engineDesc,
  transmission,
  drivetrain,
  fuelType,
  exteriorColor,
  interiorColor,
  price,
  salePrice,
  description,
  highlights,
  features,
  images,
  mpgCity,
  mpgHighway,
  warranty,
  financing,
  status,
  featured,
  slug
}`

// Query to get vehicles by make
export const VEHICLES_BY_MAKE_QUERY = `*[_type == "vehicle" && status == "available" && make == $make] | order(_createdAt desc) {
  _id,
  _type,
  title,
  year,
  make,
  model,
  trim,
  vin,
  stockNum,
  odometer,
  bodyType,
  engineDesc,
  transmission,
  drivetrain,
  fuelType,
  exteriorColor,
  interiorColor,
  price,
  salePrice,
  description,
  highlights,
  features,
  images,
  mpgCity,
  mpgHighway,
  warranty,
  financing,
  status,
  featured,
  slug
}`

// Query to get vehicles by body type
export const VEHICLES_BY_BODY_TYPE_QUERY = `*[_type == "vehicle" && status == "available" && bodyType == $bodyType] | order(_createdAt desc) {
  _id,
  _type,
  title,
  year,
  make,
  model,
  trim,
  vin,
  stockNum,
  odometer,
  bodyType,
  engineDesc,
  transmission,
  drivetrain,
  fuelType,
  exteriorColor,
  interiorColor,
  price,
  salePrice,
  description,
  highlights,
  features,
  images,
  mpgCity,
  mpgHighway,
  warranty,
  financing,
  status,
  featured,
  slug
}`

// Query to get related vehicles (same make, exclude current vehicle)
export const RELATED_VEHICLES_QUERY = `*[_type == "vehicle" && status == "available" && make == $make && _id != $excludeId] | order(_createdAt desc) [0...4] {
  _id,
  _type,
  title,
  year,
  make,
  model,
  trim,
  vin,
  stockNum,
  odometer,
  bodyType,
  engineDesc,
  transmission,
  drivetrain,
  fuelType,
  exteriorColor,
  interiorColor,
  price,
  salePrice,
  description,
  highlights,
  features,
  images,
  mpgCity,
  mpgHighway,
  warranty,
  financing,
  status,
  featured,
  slug
}`

// Query to get all unique makes for filtering
export const VEHICLE_MAKES_QUERY = `*[_type == "vehicle" && status == "available"] | order(make asc) {
  "make": make
} | [].make`

// Query to get all unique body types for filtering
export const VEHICLE_BODY_TYPES_QUERY = `*[_type == "vehicle" && status == "available"] | order(bodyType asc) {
  "bodyType": bodyType
} | [].bodyType`
